### ISSUE TITLE
Not working with most recent version of DrQA

### ISSUE THREAD

**Issue by NatCusack** [zaghaghi/drqa-webui#1]
I can't seem to get this working on the most recent version of DrQA. when the server is started, it goes through the steps of loading up the DrQA system but gets stuck on the "[ Initializing tokenizers and document retrievers... ]" step. There are no error. 

Any help would be appreciated.
Thanks!

**Comment by NatCusack** [comment]
Thanks for the speedy response! if you want any more details or anything that might help you feel free to ask :)

**Comment by zaghaghi** [comment]
Hi NatCusack,

Can you run the interactive pipeline of DrQA?
Did you try to increase `gunicorn` timeout?

thanks

**Comment by NatCusack** [comment]
yes to both, the pipeline works perfect although it takes some time to load up (using CPU only) and i have tried timeout of 800 still no luck tho

**Comment by NatCusack** [comment]
Turns out it was just a timeout problem. increased the timeout to 1200 and it worked after around 20 mins of loading.
